import { doc, setDoc } from "firebase/firestore";
import { db } from "./firebase";
import { UserProfile } from "@/types";

export const SAMPLE_USERS: UserProfile[] = [
  {
    uid: "seed_amina_algeria",
    email: "amina@zura.app",
    name: "Amina",
    age: 24,
    gender: "female",
    country: "algeria",
    city: "Algiers",
    bio: "archi sur alger, j'aime le bon café et me balader sans but précis",
    promptQuestion: "ensemble on pourrait...",
    promptAnswer: "aller tester des cafés vue sur mer et refaire le monde pendant des heures",
    lookingFor: "serious",
    interestedIn: "men",
    interests: ["Architecture", "Café", "Voyages", "Photo", "Art"],
    photo1: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    photo2: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    status: "approved",
    role: "user",
    online: true,
    isBot: true,
    lastSeen: Date.now(),
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    uid: "seed_yacine_algeria",
    email: "yacine@zura.app",
    name: "Yacine",
    age: 27,
    gender: "male",
    country: "algeria",
    city: "Oran",
    bio: "dev sur oran, passionné de foot, de sons rai et de couchers de soleil à santa cruz",
    promptQuestion: "la clé de mon coeur...",
    promptAnswer: "du bon couscous le vendredi et beaucoup de second degré",
    lookingFor: "serious",
    interestedIn: "women",
    interests: ["Tech", "Musique", "Football", "Plage", "Fitness"],
    photo1: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80",
    photo2: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    status: "approved",
    role: "user",
    online: true,
    isBot: true,
    lastSeen: Date.now(),
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    uid: "seed_kenza_morocco",
    email: "kenza@zura.app",
    name: "Kenza",
    age: 25,
    gender: "female",
    country: "morocco",
    city: "Casablanca",
    bio: "casablancaise, entre le taf en marketing et les virées sur la corniche",
    promptQuestion: "on va bien s'entendre si...",
    promptAnswer: "tu te prends pas la tête et t'aimes bien rire de tout",
    lookingFor: "casual",
    interestedIn: "men",
    interests: ["Cuisine", "Voyages", "Mode", "Musique", "Café"],
    photo1: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
    photo2: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
    status: "approved",
    role: "user",
    online: false,
    isBot: true,
    lastSeen: Date.now() - 3600000 * 2,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
  },
  {
    uid: "seed_mehdi_morocco",
    email: "mehdi@zura.app",
    name: "Mehdi",
    age: 28,
    gender: "male",
    country: "morocco",
    city: "Marrakech",
    bio: "archi & photo, toujours en train de chercher la bonne lumière et les bons spots",
    promptQuestion: "mes petits plaisirs...",
    promptAnswer: "un thé à la menthe bien chaud en terrasse avec une brise fraîche",
    lookingFor: "friends",
    interestedIn: "both",
    interests: ["Photo", "Art", "Café", "Design", "Nature"],
    photo1: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80",
    photo2: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=80",
    status: "approved",
    role: "user",
    online: true,
    isBot: true,
    lastSeen: Date.now(),
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    uid: "seed_nour_tunisia",
    email: "nour@zura.app",
    name: "Nour",
    age: 23,
    gender: "female",
    country: "tunisia",
    city: "Tunis",
    bio: "étudiante en médecine, amoureuse de sidi bou saïd et des balades au bord de l'eau",
    promptQuestion: "mon talent inutile...",
    promptAnswer: "retenir les paroles de sons que j'ai pas entendus depuis 10 ans mdr",
    lookingFor: "serious",
    interestedIn: "men",
    interests: ["Lecture", "Café", "Plage", "Nature", "Voyages"],
    photo1: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    photo2: "https://images.unsplash.com/photo-1542314831-c6a4d2757279?auto=format&fit=crop&w=800&q=80",
    status: "approved",
    role: "user",
    online: true,
    isBot: true,
    lastSeen: Date.now(),
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    uid: "seed_leila_pending",
    email: "leila@zura.app",
    name: "Leila",
    age: 22,
    gender: "female",
    country: "algeria",
    city: "Constantine",
    bio: "littérature, café chaud et discussions sans fin. juste envie de rencontrer des gens simples",
    promptQuestion: "je suis convaincue que...",
    promptAnswer: "les meilleures rencontres sont celles qu'on avait pas prévues",
    lookingFor: "friends",
    interestedIn: "both",
    interests: ["Lecture", "Écriture", "Histoire", "Café"],
    photo1: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80",
    photo2: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    status: "pending",
    role: "user",
    online: false,
    isBot: true,
    lastSeen: Date.now() - 3600000 * 12,
    createdAt: Date.now() - 3600000 * 4,
    updatedAt: Date.now() - 3600000 * 4,
  },
  {
    uid: "seed_karim_pending",
    email: "karim@zura.app",
    name: "Karim",
    age: 26,
    gender: "male",
    country: "tunisia",
    city: "Sousse",
    bio: "hôtellerie sur sousse, j'aime le sport les sorties à la mer et la bonne bouffe",
    promptQuestion: "le dimanche idéal...",
    promptAnswer: "grasse mat, grand café et virée à la plage sans regarder l'heure",
    lookingFor: "friends",
    interestedIn: "both",
    interests: ["Sport", "Plage", "Cuisine", "Fitness"],
    photo1: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80",
    photo2: "https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=800&q=80",
    status: "pending",
    role: "user",
    online: false,
    isBot: true,
    lastSeen: Date.now() - 3600000 * 8,
    createdAt: Date.now() - 3600000 * 2,
    updatedAt: Date.now() - 3600000 * 2,
  },
];

export async function seedSampleData(): Promise<number> {
  let count = 0;
  for (const user of SAMPLE_USERS) {
    await setDoc(doc(db, "users", user.uid), user);
    count++;
  }
  return count;
}

export async function promoteToAdmin(uid: string): Promise<void> {
  await setDoc(doc(db, "users", uid), { role: "admin", status: "approved" }, { merge: true });
}
